ITEM.Name = "Brahmin Skin Clothes";
ITEM.Desc = "A set of clothes made from some sort of cloth, and a jacket made from brahmin skin.";
ITEM.Model = "models/thespireroleplay/items/clothes/group004.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Clothing = true;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group004";