ITEM.Name = "Cloth Overalls";
ITEM.Desc = "Ratty, patchwork overalls with a cloth short sleeved shirt.";
ITEM.Gender = MALE;
ITEM.Model = "models/thespireroleplay/items/clothes/group015.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group023";