ITEM.Name = "Desert Combat Armor";
ITEM.Desc = "Entirely custom, this armor was made by some sort of specialist after the Great War. Offering decent protection against firearms while little to none against energy weapons, it is quite the rare set of armor.";
ITEM.Model = "models/thespireroleplay/items/clothes/group016.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 3;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_ARMOR;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group016";