ITEM.Name = "Doctor's Scrubs";
ITEM.Desc = "A dirty, white doctor's coat with pockets and a set of jeans. Usually worn by the Waste's few and far between medicine men.";
ITEM.Model = "models/thespireroleplay/items/clothes/group007.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group007";