ITEM.Name = "Pre-war Formal Wear";
ITEM.Desc = "A set of rather fancy clothes, meant for formal occasions worn by the denizens of the world before the Great War.";
ITEM.Model = "models/thespireroleplay/items/clothes/group014.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group014";