ITEM.Name = "Leather Jacket";
ITEM.Desc = "A stylish leather jacket, white t-shirt, and blue jeans.";
ITEM.Model = "models/thespireroleplay/items/clothes/group051.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.BasePrice = 999;
ITEM.Skin = 1;
ITEM.DropSkin = 1;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group051";