ITEM.Name = "Caesar's Uniform";
ITEM.Desc = "The formal uniform of the Caesar of the Legion.";
ITEM.Model = "models/thespireroleplay/items/clothes/group105.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.UseRealModelPath = true;
ITEM.Gender = MALE;
ITEM.PlayerModel = "models/thespireroleplay/humans/group105/male.mdl";
ITEM.HandsPath = "models/thespireroleplay/humans/group105/arms/male_arm.mdl";