ITEM.Name = "Mercenary Troublemaker Outfit";
ITEM.Desc = "This outfit is comprised of a heavy black coat, two ammunition belts, and some grayish pants.";
ITEM.Model = "models/thespireroleplay/items/clothes/group021.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.BasePrice = 999;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group021";