ITEM.Name = "Metal Armor";
ITEM.Desc = "A set of metal armor, made sometime after the Great War. The shoulders and wrist protectors are adorned with spikes.";
ITEM.Model = "models/thespireroleplay/items/clothes/group011.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 3;
ITEM.Clothing = true;
ITEM.Category = CATEGORY_ARMOR;
ITEM.BasePrice = 999;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group011";