ITEM.Name = "NCR Patrol Cap";
ITEM.Desc = "A hat common amongst NCR troopers. It has a set of goggles wrapped around the top.";
ITEM.Model = "models/props_junk/cardboard_box004a.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Headgear = true;
ITEM.Equipped = false;
ITEM.UseSuffix = true;
ITEM.BonemergeModel = "models/thespireroleplay/humans/headgear/ncrhats.mdl";
ITEM.Skin = 0;
ITEM.Bodygroup = 0;
ITEM.BodygroupValue = 0;