ITEM.Name = "NCR Ranger Hat";
ITEM.Desc = "A hat given out to the Rangers of the NCR.";
ITEM.Model = "models/props_junk/cardboard_box004a.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Headgear = true;
ITEM.Equipped = false;
ITEM.BonemergeModel = "models/lazarusroleplay/headgear/hats01.mdl";
ITEM.Skin = 0;
ITEM.Bodygroup = 0;
ITEM.BodygroupValue = 12;