ITEM.Name = "Dapper Pimp Suit";
ITEM.Desc = "A red formal wear that seems to be from another age. The bright colors are still quite vibrant after all this time.";
ITEM.Model = "models/thespireroleplay/items/clothes/group001.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.Clothing = true;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.BasePrice = 999;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group001";