ITEM.Name = "Stealth Suit";
ITEM.Desc = "An incredibly high-tech piece of military equipment. Meant to increase your sneaking capabilities, but no one knows if it actually does.";
ITEM.Model = "models/thespireroleplay/items/clothes/group005.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 3;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_ARMOR;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group005";