ITEM.Name = "SWAT Vest";
ITEM.Desc = "A SLCPD SWAT Tactical Vest over dust-worn jeans and a button-up shirt.";
ITEM.Model = "models/thespireroleplay/items/clothes/group002.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.BasePrice = 999;
ITEM.Category = CATEGORY_ARMOR;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group002";