ITEM.Name = "Vault 101 Jumpsuit";
ITEM.Desc = "A classic Vault-Boy blue and yellow jumpsuit worn by Vault Dwellers across the wastes. This one has the number '101' embroidered on the collar and back.";
ITEM.Model = "models/thespireroleplay/items/clothes/group010.mdl";
ITEM.EquipSound = "fallout/items/clothing/ui_items_clothing_up_01.wav"
ITEM.UnequipSound = "fallout/items/clothing/ui_items_clothing_down_01.wav"
ITEM.W = 2;
ITEM.H = 2;
ITEM.Category = CATEGORY_CLOTHING;
ITEM.BasePrice = 999;
ITEM.Clothing = true;
ITEM.Equipped = false;
ITEM.PlayerModel = "models/thespireroleplay/humans/group010";