--[[
	2011 Slidefuse Networks; Do NOT Share/Distribute/Modify
	Author: Spencer Sharkey (spencer@sf-n.com)
--]]

require("tmysql");
require("json");

AddCSLuaFile("shared.lua");
AddCSLuaFile("cl_init.lua");

include("shared.lua");

--[[
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhysssdo:/::yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds+/+ooos+:/yy::mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs+oo++:::/o:://:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo+:::/+++oooo+odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+:/+oo+++/++///+omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/so+/+ooooso////++dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMmd///+os+++h//s+sosMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMNNNMMMMMMMNo//s:/--:y//++//hMMMNMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNMMMMMNNNNNNMMMMMMMNNNNNMMMMMMh//++++ooo///++oymNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNNNMMMNNNNNNNNNNNMMMNNNNNNMMMMm/////++///+/++/+ohNNNNNNNMMNNMMMMMMMMMNNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNNNNMMNNNNNNNNNNNNNMNNNNNNNNNm//sdmmdo//oo/oo/somNNNNMMNNNNMMMMMMmhsoyNMMMMMMMMMMMMMM
MMMMMMMMMNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNm/sNmmNNh//so//y/s+sNNNNNNNNNNMMMMNy+//sNMMMMMMMMMMMMMMM
MMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNmdyyyhdoy/+ssssy+//y//oy+sdmNNNNNNNNNNMMMNs//++mMMMMMMMMMMMMMMMM
MMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNds:-.::.--o+/////+o++sosoysdmNNNNNNNNNNNNNNm///+oyhmmmNNNNNNNNMMMM
MMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNdo-...../:...+o++++++++++y.../osdNNNNNNNNNd+ys//////+++osossssoNMMMN
MMMMMMMMMMMMMMNNNNNNNNNNNNNNNNd+-........o....:oo++///y/+s....o.-+dmNNNmdo:.y/////////////////yMMMMM
MMMMMMMMMMMMMMNNNNNNNNNNNNNNh+-..........o......:+o+++y+y-....:/..:yhdy+-...o+//////////////+hNMMMMM
MMMMMMMMMMMMMMMMMMMNNNNNNNd+-............o........:++/:+/......o..--:-.......s//o+/////+++oymMMMMMMM
MMMMMMMMMMMMMMMMNNNNNNNNmo-..............o..........-+o:.......s.............-oo/:odddddmNMMMMMMMMMM
MMMMMMMMMMMMMMMMNNNNNNNd:................o.........-//-........s...............:::hNNNMMMMMMMMMMMMMM
MMMMMMMMMMMMMNNMMMNNNNd-...............-/:.......-//-..........s..............:ydmNNNNNNNNNMMMMMMMMM
MMMMMMMMMMMMMMNNNNNNNN+...---..----.-//+:---:--+oo//-.//++/.:++y+--/ooooo/-/osmmmmmNNNNMMMMMMMMMMMMM
MMMMMMMMMMMMMMmmdmNmddss:ssooshoooyhho++ds++/dhh/::ysoy---ohm-..ody+.```./hm.``````/NMMMMMMMMMMMMMMM
MMMMMMMNNNNNNN.``.No```smy```/d```oNo```ho```om.``-m:so````hm```od.```.```-d```````+NNNNNMMMMMMMMMMM
MMMMMMMMMNNNNN/```dh```/N/```hd```oNo```hm.``./```d+.so````.d```oo```hN-```mmy```oNNNNNMMMMMMMMMMMMM
MMMMMMMMMMMNNNo```+N.``-m.``.Nh```./.```mNy``````yy..y+`````:```s+```dN-```mNy```sNNNNNNNMMMMMMMMMMM
MMMMMMMMNMMMNNm```.h````s```sNh`````````NNN-````/d//:h+`````````h/```mN-``.NNs```sNNNNNNNNMMMMMMMMMM
MMMMMMMNNNNNNNN:```.```````-NNy```./.```NNNy```-m/.-:d:``.+`````h/```dN-``.NNs```sNNNNNNMMMMMMMMMMMM
MMMMMMMMNNNNNNNs```````````sNNs```yN+```NNNh```oy...-m-``.m-````do```:/```+NNo```yNNNNNNNNMMMMMMMMMN
MMMMMMMMNNNNNNNm`````/````.NNNo```hN:```NNNy```os....m.``-Nh````mm-``````/mNN+```yNNNNNNNNMMMMMMMMMN
MMMNNNNNNNNNNNNN:```om.```yNNNs--:dN+//+NNNd+++do---.dsssyNNysyyNNNhsosymNNNNmhddNNNmmNNNNNNNNMMMMMN
MMMMNNNNNNNNNNNNmhhhmNmdmmmmddmmhyhyysymNNNmsooo+++osNNd++++////md/////:/+smNNNmy/-....-NN-...:hMMMN
MMMMs::::-:-/NNho-..../yNN:...+h```````.+mNy`````````+Ny````````ds`````````:mNh-````````Nd`````:NMMN
NMMM:```````-No.````````sN.```oh````.````-Ns```-s+````ms````+oosNo```.o/````yd.```:syyosNNmd.``:NMMN
NMMMhss+````hm.```oh:```:N.```sy```.ds````yo```-yo```.mo```.yyyhNo```:Nh````y+```.ms++++dNNd``.dMMMN
NMMMMMm:```yNd````dN+```:m````ys```-NN````s+````````.hNo```````-N+```.s/````d-```/N`````yNN/``hNMMMN
MMMMMN:```yNNh````mN/```/m````ys```-NN````s+````-````:mo````---/N/`````````+N.```/N+-```hNm``:NMMMMN
NMMMN+```oNNNy````mN/```/m````hs```-Nm````y+```+mh````y+```-mmmNN/````````sNN/````hNo```hNN::oNMMMMN
NMMNo```/mNNNh````dm:```om````hs```.h/```:N+```:s/````y+````:://m:```++```-mNh.```.-.```dNNhhhNMMMMN
NMMy````-:--/m.```--```.dd````ds````````:mN/`````````+N:````````d-```sm-```:NNh:````````mNy```NMMMMN
NMM:````````-Ny-`````.:hNd....ms.----:/yNNNs://///+sdNNy++++ooooNsoosmNdsyyyNNNNdysoosshNMd+ooMMMMMM
MMMhooooossyhMMmhyyyhdNNNNmmmmMNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNNNMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNNNNNNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNNNNMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMNNNNNNNMNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMNNNNNNMMNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNMMMMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
]]--