--[[
	Free Clockwork!
--]]

Clockwork.config:AddToSystem("mysql_characters_table", "The name of the table where the character data is stored.");
Clockwork.config:AddToSystem("mysql_players_table", "The name of the table where the player data is stored.");
Clockwork.config:AddToSystem("mysql_username", "The username that you log in to MySQL with.");
Clockwork.config:AddToSystem("mysql_password", "The password that you log in to MySQL with.");
Clockwork.config:AddToSystem("mysql_database", "The name of the database that we'll be using.");
Clockwork.config:AddToSystem("mysql_host", "The host that your MySQL database is located.");
Clockwork.config:AddToSystem("scale_attribute_progress", "The amount to scale attribute progress by.");
Clockwork.config:AddToSystem("messages_must_see_player", "The amount to scale attribute progress by.");
Clockwork.config:AddToSystem("messages_must_see_player", "Whether or not you must see a player to hear some in-character messages.");
Clockwork.config:AddToSystem("default_attribute_points", "The default amount of attribute points that a player has.");
Clockwork.config:AddToSystem("clockwork_intro_enabled", "Enable the Clockwork introduction for new players.");
Clockwork.config:AddToSystem("enable_temporary_damage", "Whether or not temporary damage is enabled.");
Clockwork.config:AddToSystem("enable_prop_protection", "Whether or not to enable prop protection.");
Clockwork.config:AddToSystem("use_local_machine_date", "Whether or not to use the local machine's date when the map is loaded.");
Clockwork.config:AddToSystem("use_local_machine_time", "Whether or not to use the local machine's time when the map is loaded.");
Clockwork.config:AddToSystem("use_opens_entity_menus", "Whether or not 'use' opens the context menus.");
Clockwork.config:AddToSystem("shoot_after_raise_time", "The time that it takes for players to be able to shoot after raising their weapon (seconds).\nSet to 0 for no time.");
Clockwork.config:AddToSystem("use_own_group_system", "Whether or not you use a different group or admin system to Clockwork.");
Clockwork.config:AddToSystem("save_recognised_names", "Whether or not recognised names should be saved.");
Clockwork.config:AddToSystem("save_attribute_boosts", "Whether or not attribute boosts are saved.");
Clockwork.config:AddToSystem("ragdoll_immunity_time", "The time that a player's ragdoll is immune from damage (seconds).");
Clockwork.config:AddToSystem("additional_characters", "The additional amount of characters that each player can have.");
Clockwork.config:AddToSystem("change_class_interval", "The time that a player has to wait to change class again (seconds).", 0, 7200);
Clockwork.config:AddToSystem("sprint_lowers_weapon", "Whether or not sprinting lowers a player's weapon.");
Clockwork.config:AddToSystem("raised_weapon_system", "Whether or not the raised weapon system is enabled.");
Clockwork.config:AddToSystem("prop_kill_protection", "Whether or not prop kill protection is enabled.");
Clockwork.config:AddToSystem("use_optimised_rates", "Whether or not to use Clockwork optimised rates.");
Clockwork.config:AddToSystem("generator_interval", "The time that it takes for generator cash to be distrubuted (seconds).", 0, 7200);
Clockwork.config:AddToSystem("enable_gravgun_punt", "Whether or not to enable entities to be punted with the gravity gun.");
Clockwork.config:AddToSystem("default_inv_weight", "The default inventory weight (kilograms).");
Clockwork.config:AddToSystem("save_data_interval", "The time that it takes for data to be saved (seconds).", 0, 7200);
Clockwork.config:AddToSystem("damage_view_punch", "Whether or not a player's view gets punched when they take damage.");
Clockwork.config:AddToSystem("unrecognised_name", "The name that is given to unrecognised players.");
Clockwork.config:AddToSystem("limb_damage_system", "Whether or not limb damage is enabled.");
Clockwork.config:AddToSystem("scale_fall_damage", "The amount to scale fall damage by.");
Clockwork.config:AddToSystem("default_cash", "The default amount of cash that each player starts with.", 0, 10000);
Clockwork.config:AddToSystem("armor_chest_only", "Whether or not armor only affects the chest.");
Clockwork.config:AddToSystem("minimum_physdesc", "The minimum amount of characters a player must have in their physical description.", 0, 128);
Clockwork.config:AddToSystem("wood_breaks_fall", "Whether or not wooden physics entities break a player's fall.");
Clockwork.config:AddToSystem("enable_vignette", "Whether or not the vignette is enabled.");
Clockwork.config:AddToSystem("enable_heartbeat", "Whether or not the heartbeat is enabled.");
Clockwork.config:AddToSystem("enable_crosshair", "Whether or not the crosshair is enabled.");
Clockwork.config:AddToSystem("use_free_aiming", "Whether or not free aiming is enabled.");
Clockwork.config:AddToSystem("recognise_system", "Whether or not the recognise system is enabled.");
Clockwork.config:AddToSystem("cash_enabled", "Whether or not cash is enabled.");
Clockwork.config:AddToSystem("default_physdesc", "The physical description that each player begins with.");
Clockwork.config:AddToSystem("scale_chest_dmg", "The amount to scale chest damage by.");
Clockwork.config:AddToSystem("body_decay_time", "The time that it takes for a player's ragdoll to decay (seconds).", 0, 7200);
Clockwork.config:AddToSystem("banned_message", "The message that a player receives when trying to join while banned.\n!t for the time left, !f for the time format.");
Clockwork.config:AddToSystem("wages_interval", "The time that it takes for wages cash to be distrubuted (seconds).", 0, 7200);
Clockwork.config:AddToSystem("scale_prop_cost", "How to much to scale prop cost by.\nSet to 0 to to make props free.");
Clockwork.config:AddToSystem("fade_dead_npcs", "Whether or not to fade dead NPCs.");
Clockwork.config:AddToSystem("cash_weight", "The weight of cash (kilograms).", 0, 100, 3);
Clockwork.config:AddToSystem("scale_head_dmg", "The amount to scale head damage by.");
Clockwork.config:AddToSystem("block_inv_binds", "Whether or not inventory binds should be blocked for players.");
Clockwork.config:AddToSystem("scale_limb_dmg", "The amount to scale limb damage by.");
Clockwork.config:AddToSystem("enable_headbob", "Whether or not to enable headbob.");
Clockwork.config:AddToSystem("command_prefix", "The prefix that is used for chat commands.");
Clockwork.config:AddToSystem("crouched_speed", "The speed that characters walk at when crouched.", 0, 1024);
Clockwork.config:AddToSystem("owner_steamid", "The Steam ID of the server owner.");
Clockwork.config:AddToSystem("default_flags", "The flags that each player begins with.");
Clockwork.config:AddToSystem("disable_sprays", "Whether players can spray their tags.");
Clockwork.config:AddToSystem("hint_interval", "The time that a hint is displayed to each player (seconds).", 0, 7200);
Clockwork.config:AddToSystem("ooc_interval", "The time that a player has to wait to speak out-of-character again (seconds).\nSet to 0 for never.", 0, 7200);
Clockwork.config:AddToSystem("minute_time", "The time that it takes for a minute to pass (seconds).", 0, 7200);
Clockwork.config:AddToSystem("unlock_time", "The time that a player has to wait to unlock a door (seconds).", 0, 7200);
Clockwork.config:AddToSystem("local_voice", "Whether or not to enable local voice.");
Clockwork.config:AddToSystem("talk_radius", "The radius of each player that other characters have to be in to hear them talk (units).", 0, 4096);
Clockwork.config:AddToSystem("give_hands", "Whether or not to give hands to each player.");
Clockwork.config:AddToSystem("give_keys", "Whether or not to give keys to each player.");
Clockwork.config:AddToSystem("wages_name", "The name that is given to wages.");
Clockwork.config:AddToSystem("jump_power", "The power that characters jump at.", 0, 1024);
Clockwork.config:AddToSystem("spawn_time", "The time that a player has to wait before they can spawn again (seconds).", 0, 7200);
Clockwork.config:AddToSystem("walk_speed", "The speed that characters walk at.", 0, 1024);
Clockwork.config:AddToSystem("run_speed", "The speed that characters run at.", 0, 1024);
Clockwork.config:AddToSystem("door_cost", "The amount of cash that each door costs.");
Clockwork.config:AddToSystem("lock_time", "The time that a player has to wait to lock a door (seconds).", 0, 7200);
Clockwork.config:AddToSystem("max_doors", "The maximum amount of doors a player can own.");