STEAMID_RUSTY = "STEAM_0:0:2774134";
STEAMID_SOUP = "STEAM_0:1:41495393";
STEAMID_SCOOBS = "STEAM_0:1:44216089";

MALE = 1;
FEMALE = 2;

CHARCREATE_SELECT = 1;
CHARCREATE_DELETE = 2;
CHARCREATE_SELECTCLASS = 3;
CHARCREATE_SURVIVOR = 4;
CHARCREATE_SUPERMUTANT = 5;
CHARCREATE_ANIMAL = 6;

SONG_LIGHT = 1;
SONG_MEDIUM = 2;
SONG_HEAVY = 3;

IRON_HOLSTERED = 0;
IRON_HOLSTERED2IDLE = 1;
IRON_IDLE = 2;
IRON_IDLE2AIM = 3;
IRON_AIM = 4;

CATEGORY_PRIMARYWEAPON = 1;
CATEGORY_SECONDARYWEAPON = 2;
CATEGORY_CLOTHING = 3;
CATEGORY_ARMOR = 4;
CATEGORY_AMMO = 5;
CATEGORY_FOOD = 6;
CATEGORY_MEDICAL = 7;
CATEGORY_MISC = 8;

TEAM_SURVIVOR = 1;

CB_ALL = 1;
CB_IC = 2;
CB_OOC = 3;
CB_RADIO = 4;
CB_PM = 5;

COLOR_ERROR = Color( 255, 0, 0, 255 );
COLOR_NOTIFY = Color( 255, 200, 75, 255 );

PLAYERCLASS_SURVIVOR = 1;
PLAYERCLASS_SUPERMUTANT = 2;
PLAYERCLASS_ANIMAL = 3;

SI_JUMPER = 1;
SI_SCREAMER = 2;